#ifndef tags_h
#define tags_h
enum TAGS { H_BEGIN=110, H_END, H_P_MOVE_REQUEST, P_H_MOVE, H_W_BOARD_UPDATE_REQUEST, W_H_BOARD_UPDATE, H_P_BOARD, H_P_SNAKES, H_W_BOARD_SECTION, W_W_BOARD_SECTION };
enum COLOR_IXS {WHITE=0,BLACK,DGREEN,CYAN,RED,YELLOW,GOLD,GREEN,GREENISH,INDIGO,LGREEN,LPURPLE,ORANGE,PUCE,PURPLE,BLUE,TEAL,VOMIT,BEIGE};
enum DIRS{ UP=130, DOWN, LEFT, RIGHT, STOP };
#endif
